// src/lib/templateConfig.ts
import { TemplateConfig } from "./custom_types";

export const templateConfig: { [key: string]: TemplateConfig } = {
  'garden-wedding': {
    name: 'Boda en el Jardín',
    thumbnail: '/branding/portadas/portada-garden.png',
    category: 'Boda',
    description: 'A romantic and elegant template for a garden wedding, with a classic, sophisticated feel.',
    font: 'font-serif',
    defaultFont: 'Playfair Display',
    fonts: ['Playfair Display', 'Lora', 'Cormorant Garamond'],
    palettes: [
      { name: 'Garden Green', primary: '#646f58', text: '#292524', background: '#Fdfbf5', secondary: '#8c8470', dark: '#f0eee4' },
    ],
    defaultData: {
      primaryColor: '#646f58',
      textColor: '#292524',
      backgroundColor: '#Fdfbf5',
      secondaryColor: '#8c8470',
      buttonTextColor: '#f0eee4',
      heroTitle: "Acompáñanos a celebrar la boda de",
      partner1Name: "Alicia",
      partner2Name: "Oliver",
      event_date: "2026-11-07T16:30:00",
      locationName: "Villa Cantacuzino",
      venue_city: "Valle de Guadalupe, B.C., México",
      heroSubtitle: "Estamos listos para unir nuestro amor",
      receptionTitle: "Prepárate para la celebración",
      timelineTitle: "Programa del Día",
      timelineItems: [
        { time: '15:30', title: 'Misa', location: 'Iglesia Santa Maria Reina' },
        { time: '16:30', title: 'Recepción de Invitados', location: 'Viñedos L.A Cetto' },
        { time: '17:30', title: 'Banquete', location: 'Viñedos L.A Cetto' },
        { time: '22:00', title: 'Pastel', location: 'El dulce símbolo de nuestra nueva vida' },
        { time: '02:00', title: 'Fin de la Fiesta', location: 'Incluso una noche tan maravillosa llega a su fin' },
      ],
      mainVenueAddress: 'Dirección del Evento',
      receptionText: 'Nuestra boda se llevará a cabo en: Villa Cantacuzino, Valle de Guadalupe, Baja California, México. ¡Esperamos verlos allí para celebrar juntos!',
      receptionPlace: 'VER EN MAPA',
      dressCodeTitle: 'Código de Vestimenta',
      giftRegistryUrl: 'Regalos',
      giftTitle: 'Mesa de Regalos',
      giftMessage: 'Tu presencia es nuestro mayor regalo. Pero si deseas obsequiarnos algo, hemos preparado una mesa de regalos con cariño.',
      giftButtonText: 'Ver Opciones de Regalo',
      dressCodeDetails: 'Vestimental Formal, elegante y con un toque de color en tonos otoñales. Puedes ver los siguientes links para inspirarte en tu atuendo',
      futurePlans: 'Agradecemos su presencia en un día tan especial para nosotros y esperamos que puedan acompañarnos en esta nueva etapa de nuestras vidas.',
      galleryImages: [
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/oldMoney/fondo-oldmoney.jpg",
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Romantic/romantic-4.jpg",
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Romantic/romantic-5.jpg",
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/oldMoney/oldMoney3.png",
      ],
      parentalNotesTitle: 'Pequeños Invitados',
      parentalNotes: 'Por favor, dejad a los niños en buenas manos durante la noche de nuestra celebración, ya que el formato no incluye zona infantil ni animadores.',
      dressCode: {
        woman: 'Vestidos en tonos pastel.',
        man: 'Traje o una combinación de los siguientes elementos:<br />Pantalones: pantalones de vestir, chinos, slacks<br />o shorts.'
      },
      heroNames: "Alicia & Oliver",
    },
    features: {
      multiEventSchedule: true,
      dressCode: true,
      rsvp: true,
      guestCount: true,
      gallery: true,
    },
    formSections: [
      'main-details',
      'colors-and-style',
      'event-schedule',
      'dress-code',
      'gift-section',
      'gift-registry',
    ],
  },
  "timeline-wedding": {
    name: "Boda - Estilo Elegante",
    thumbnail: "/branding/portadas/portada-elegante.png",
    category: "Boda",
    description: "A beautiful, scrolling story of your special day.",
    font: "font-serif",
    defaultFont: "Playfair Display",
    fonts: ["Playfair Display", "Lora", "Merriweather", "Cormorant Garamond"],
    palettes: [
      { name: "Amethyst", primary: "#F7F5F0", text: "#374151", background: "#ffffff" },
      { name: "Rose Gold", primary: "#b45309", text: "#4b5563", background: "#ffffff" },
      { name: "Emerald", primary: "#047857", text: "#374151", background: "#ffffff" },
    ],
    defaultData: {
      primaryColor: "#8F9779",
      textColor: "#374151",
      backgroundColor: "#e7dfd6",
      hero_image_url:
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Timeline/timeline-portada.jpg",
      heroTitle: "La Boda De",
      heroNames: "Andrea & Jhon",
      timelineTitle: "Nuestro dia de boda",
      galleryTitle: "Nuestra Historia",
      dressCode: {
        man: "Formal",
        woman: "Formal",
        pinterestUrlMan: "https://pin.it/5hSkwuONE",
        pinterestUrlWoman: "https://pin.it/57zbcpMb7",
      },
      locationName: "The Grand Hall",
      mainVenueAddress: "123 Calle Principal, Ciudad, MX",
      event_date: "2026-10-27T18:00:00",
      giftRegistryUrl: "https://www.amazon.com",
      giftTitle: "Mesa de Regalos",
      giftMessage: "Tu presencia es nuestro mayor regalo. Pero si deseas obsequiarnos algo, hemos preparado una mesa de regalos con cariño.",
      giftButtonText: "Ver Opciones de Regalo",
      galleryImages: [
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Timeline/timeline-portada.jpg",
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Timeline/timeline-3.jpg",
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Timeline/timeline-1.jpg",
      ],
      recommendations: [
        {
          name: "The Grand Hotel",
          description: "Hotel 5-estrellas cerca de la fiesta.",
          link: "",
        },
        {
          name: "City Center Inn",
          description: "Opción en el centro.",
          link: "",
        },
        {
          name: "Comida",
          description: "Guía de los mejores restaurantes locales.",
          link: "",
        },
        {
          name: "Lugares para Visitar",
          description: "Guía de los mejores lugares para visitar.",
          link: "",
        },
      ],
      timelineItems: [
        {
          time: "3 PM",
          title: "Ceremonia",
          location: "Iglesia de Santa María",
        },
        {
          time: "4 PM",
          title: "Recepción",
          location: "Los Jardines del Gran Salón",
        },
        {
          time: "6 PM",
          title: "Cena y Baile",
          location: "Los Jardines del Gran Salón",
        },
        { time: "9 PM", title: "Tornaboda", location: "Hacienda San José" },
      ],
    },
    features: {
      multiEventSchedule: true,
      countdown: { type: "flip-clock" },
      recommendations: true,
      digitalRegistry: { enabled: true, types: ["amazon", "cash_fund"] },
      songRequests: true,
      gallery: true,
      guestCount: true,
    },
    formSections: [
      "main-details",
      "colors-and-style",
      "event-schedule",
      "recommendations",
      "dress-code",
      "gift-section",
      "gallery",
      "gift-registry"
    ],
  },
  'wedding-aquarrel': {
    name: 'Boda - Estilo Acuarela',
    description: 'A romantic, artistic template featuring watercolor illustrations and elegant typography.',
    category: 'Boda',
    thumbnail: '/save-date-acuarela.jpg',
    font: 'font-serif',
    defaultFont: 'Playfair Display',
    fonts: ["Playfair Display", "Lora", "Merriweather", "Cormorant Garamond"],
    palettes: [
      { name: "Amethyst", primary: "#A39171", text: "#333333", background: "#FDFBF7" },
    ],
    defaultData: {
      backgroundColor: "#FDFBF7",
      textColor: "#333333",
      primaryColor: "#A39171",
      heroTitle: "SAVE THE DATE",
      heroNames: "Mark & Lindsay",
      event_date: "2025-07-21T15:00:00.000Z",
      mainVenueAddress: "Willow Chapel, 93 Street, Toronto, ON",
      locationName: "Willow Chapel",
      timelineTitle: "Wedding Details",
      guestCount: "2",
      galleryImages: [
        'https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/oldMoney/oldMoney2.png',
        'https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/oldMoney/oldMoney1.png',
        'https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/oldMoney/fondo-oldmoney.jpg'
      ],
      timelineItems: [
        {
          title: "The Ceremony",
          time: "3:00 PM",
          location: "Willow Chapel, 93 Street, Toronto, ON",
          imageSrc: "/acuarela1.jpg",
          imageAlt: "Watercolor Church Ceremony",
        },
        {
          title: "The Reception",
          time: "5:00 PM (Cocktails) | 6:30 PM (Dinner)",
          location: "The Great Hall, 95 Street, Toronto, ON",
          imageSrc: "/acuarela2.jpg",
          imageAlt: "Watercolor Dinner Reception",
        },
      ],
    },
    features: {
      multiEventSchedule: true,
      gallery: true,
      dressCode: false,
      recommendations: false,
      guestCount: true,
    },
    formSections: [
      'main-details',
      'colors-and-style',
      'event-schedule',
      'gallery',
      'guest-count',
    ]
  },
  "minimalist-wedding": {
    name: "Boda - Estilo Blanco & Negro",
    thumbnail: "/branding/portadas/portada-bnw.png",
    category: "Boda",
    description: "Clean, modern, and elegant. For the minimalist couple.",
    font: "font-sans",
    defaultFont: "Montserrat",
    fonts: ["Montserrat", "Poppins", "Lato", "Open Sans"],
    palettes: [
      { name: "Black & White", primary: "#111827", text: "#6b7280", background: "#ffffff" },
      { name: "Dusty Blue", primary: "#60a5fa", text: "#4b5563", background: "#ffffff" },
      { name: "Terracotta", primary: "#f59e0b", text: "#374151", background: "#ffffff" },
    ],
    defaultData: {
      primaryColor: "#111827",
      textColor: "#6b7280",
      backgroundColor: "#f3f4f6",
      hero_image_url:
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Portadas/portada-bnw.png",
      heroTitle: "Juntos en familia",
      heroNames: "Olivia & Liam",
      timelineTitle: "La Celebración",
      galleryTitle: "Nuestra Historia",
      dressCode: {
        man: "Formal",
        woman: "Formal",
        pinterestUrlMan: "https://pin.it/5hSkwuONE",
        pinterestUrlWoman: "https://pin.it/57zbcpMb7",
      },
      locationName: "The Modern",
      mainVenueAddress: "The Modern Art Museum, New York",
      event_date: "2026-10-27T18:00:00",
      giftRegistryUrl: "https://www.google.com",
      galleryImages: [
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/BnW/bnw-1.jpg",
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/BnW/bnw-2.jpg",
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/BnW/bnw-3.jpg",
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/BnW/bnw-4.jpg",
      ],
      timelineItems: [
        {
          time: "5 PM",
          title: "Boda Civil",
          location: "Los Jardines del Gran Salón",
        },
        { time: "6 PM", title: "Cócteles", location: "El Gran Salón" },
        {
          time: "7 PM",
          title: "Cena y Baile",
          location: "Los Jardines del Gran Salón",
        },
      ],
    },
    features: {
      multiEventSchedule: true,
      recommendations: true,
      gallery: true,
      guestCount: true,
    },
    formSections: [
      'main-details',
      'colors-and-style',
      'dress-code',
      'event-schedule',
      'gallery',
    ],
  },

  "quinceanera-dream": {
    name: "XV Años",
    thumbnail: "/branding/portadas/portada-quince.png",
    category: "XV Años",
    description:
      "Tu celebración de XV años hecha realidad en una invitación digital.",
    font: "font-serif",
    defaultFont: "Dancing Script",
    fonts: ["Dancing Script", "Great Vibes", "Parisienne", "Alex Brush"],
    palettes: [
      { name: "Pink Dream", primary: "#db2777", text: "#374151", background: "#ffffff" },
      { name: "Royal Gold", primary: "#ca8a04", text: "#46dfd2", background: "#ffffff" },
      { name: "Lilac", primary: "#8b5cf6", text: "#f9fafb", background: "#ffffff" },
    ],
    defaultData: {
      primaryColor: "#e61875",
      textColor: "#242222",
      backgroundColor: "#f4f1e7",
      hero_image_url:
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Quince/quince-1.jpg",
      heroTitle: "Estás invitado a los XV de",
      heroNames: "Valentina",
      timelineTitle: "La Celebración",
      galleryTitle: "Mi Álbum de XV",
      courtOfHonor: [
        {
          name: "Mateo",
          role: "Chambelán",
          photoUrl: "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Quince/chambe.png",
        },
        {
          name: "Sofia",
          role: "Dama",
          photoUrl: "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Quince/friend1.png",
        },
        {
          name: "Dani",
          role: "Dama",
          photoUrl: "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Quince/friend2.png",
        },
         {
          name: "Andrea",
          role: "Dama",
          photoUrl: "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Quince/friend3.png",
        },
      ],
      timelineItems: [
        { time: "5 PM", title: "Misa", location: "Iglesia San Juan Bautista" },
        {
          time: "7 PM",
          title: "Cena",
          location: "Salón Crystal Palace",
        },
        {
          time: "9 PM",
          title: "Música y Baile",
          location: "Salón Crystal Palace",
        },
      ],
    },
    features: {
      courtOfHonor: true,
      uniqueCeremonies: true,
      socialMediaWall: true,
    },
  },
  "kids-birthday-bash": {
    name: "Fiesta de Cumpleaños Infantil",
    thumbnail: "/branding/portadas/portada-bdy2.png",
    category: "Cumpleaños Infantil",
    description: "Una fiesta divertida y temática para los más pequeños.",
    font: "font-sans",
    defaultFont: "Nunito",
    fonts: ["Nunito", "Quicksand", "Comfortaa", "Fredoka One"],
    palettes: [
      { name: "Superhéroe", primary: "#2563eb", text: "#1f2937", background: "#ffffff" },
      { name: "Dinosaurio", primary: "#16a34a", text: "#ffa12e", background: "#ffffff" },
      { name: "Unicornio", primary: "#ec4899", text: "#e3b1ee", background: "#ffffff" },
    ],
    defaultData: {
      primaryColor: "#2563eb",
      textColor: "#1f2937",
      backgroundColor: "#6366F1",
      hero_image_url:
        "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?q=80&w=2070&auto=format&fit=crop",
      heroTitle: "Únete a la Celebración",
      heroNames: "¡5º Cumple de Leo!",
      timelineTitle: "¡Hora de la Fiesta!",
      dateSubtitle: "¡No podemos esperar para celebrar contigo!",
      event_date: "2026-08-15T14:00:00",
      location: "Salón Arcoíris, Av. de la Alegría 123, CDMX",
      timelineItems: [
        {
          time: "2 PM",
          title: "Comida y Entretenimiento",
          location: "JumpZone Play Park",
        },
        {
          time: "4 PM",
          title: "Pastel y Regalos",
          location: "JumpZone Party Room",
        },
      ],
      parentalNotes:
        "Se requieren calcetines para el área de juegos. La recogida es a las 5 PM.",

      // ADD THE IMAGES ARRAY HERE:
      galleryImages: [
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Kids-Bdy/kids-boy-1.jpg",
        "https://images.unsplash.com/photo-1517164850305-99a3e65bb47e?q=80&w=500",
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Kids-Bdy/bdy-kids-1.jpg",
      ],
    },
    features: {
      ageSpecificThemes: ["superhero", "boho"],
      parentalNotes: true,
      allergyTracker: true,
      gallery: true,
    },
  },
  "baptism-ethereal": {
    name: "Bautizo",
    thumbnail: "/branding/portadas/portada-bautizo.png",
    category: "Baby Shower",
    description: "Un diseño sereno y etéreo para bautizos.",
    font: "font-serif",
    defaultFont: "Cormorant Garamond",
    fonts: ["Cormorant Garamond", "Lora", "Playfair Display"],
    palettes: [
      { name: "Sacred White", primary: "#d1a36a", text: "#a27b5c", background: "#ffffff" },
      { name: "Divine Gold", primary: "#d4d4d8", text: "#71717a", background: "#ffffff" },
    ],
    defaultData: {
      primaryColor: "#d1a36a",
      textColor: "#a27b5c",
      backgroundColor: "#fcfbf7",
      heroTitle: "Una Celebración Sagrada",
      heroNames: "Andrea Fernandez",
      timelineTitle: "Detalles del Evento",
      event_date: "2026-04-25T11:00:00",
      timelineItems: [
        {
          time: "11 AM",
          title: "Ceremonia",
          location: "Catedral de la Gracia\n123 Grace Ave, City",
          mapLink: "",
        },
        {
          time: "1 PM",
          title: "Recepción",
          location: "El Conservatorio\n456 Garden St, City",
          mapLink: "",
        },
      ],
      locationName: "Catedral de la Gracia",
      mainVenueAddress: "123 Grace Ave, City",
      parentsTitle: 'Con la bendición de mis padres',
      parentsSectionTitle: 'Mis Padres',
      partner1Parents: ['Nombre Padre', 'Nombre Madre'],
      partner2Parents: [],
      godparentsSubtitle: 'Guías de Fe',
      godparentsTitle: 'Mis Padrinos',
      godparents: [
        { role: 'Madrina', name: 'Elizabeth Montgomery' },
        { role: 'Padrino', name: 'Christopher Rhodes' },
      ],
      receptionTitle: 'Recepción',
      receptionText: '"Después de la bendición sagrada, acompáñanos a celebrar con un brindis especial en honor a Sofía."',
      receptionPlace: 'Lugar: Jardín de los Rosales Conservatorio',
      giftRegistryUrl: 'https://www.amazon.com',
      giftTitle: 'Mesa de Regalos',
      giftMessage: 'Tu presencia es nuestro mayor regalo, pero si deseas obsequiarnos algo, hemos preparado una mesa de regalos con cariño.',
      giftButtonText: 'Ver Mesa de Regalos',
    },
    features: {
      multiEventSchedule: true,
      parentsAndGodparents: true,
    },
    formSections: [
      'main-details',
      'colors-and-style',
      'event-schedule',
      'parents-godparents',
      'gift-registry',
      'closing-card'
    ],
  },
    "gender-reveal-party": {
    name: "Revelación de Género - Clásica",
    thumbnail: "/branding/portadas/portada-gender.png",
    category: "Baby Shower",
    description:
      "¿Niño o Niña? ¡Ven y descúbrelo! Una fiesta divertida para revelar el género de nuestro bebé.",
    font: "font-sans",
    defaultFont: "Montserrat",
    fonts: ["Montserrat", "Poppins", "Lato", "Open Sans"],
    palettes: [
      { name: "Blue & Pink", primary: "#3b82f6", text: "#ec4899", background: "#ffffff" },
      { name: "Pastel", primary: "#a2cdf5", text: "#fa82be", background: "#ffffff" },
      { name: "Sunshine", primary: "#f4df73", text: "#ff8262", background: "#ffffff" },
    ],
    defaultData: {
      primaryColor: "#3b82f6",
      textColor: "#ec4899",
      backgroundColor: "#fef3f4",
      family_image_url:
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/gender-reveal/gender-1.jpg",
      heroTitle: "¡Niño o Niña?",
      heroNames: "Acompáñanos a descubrirlo",
      heroSubtitle:
        "Acompañanos a celebrar la dulce espera de nuestro bebé con una divertida revelación de género. ¡Será un día lleno de amor, risas y sorpresas!",
      parentsDescription: `"Nuestros corazones están atrapados entre suaves atardeceres rosados y cielos azules cristalinos. ¡No podemos esperar para compartir esta mágica
        revelación con las personas que más amamos!"`,
      timelineTitle: "Detalles de la Fiesta",
      locationName: "Nuestra Casa",
      mainVenueAddress: "123 Calle Principal, Ciudad, MX",
      event_date: "2026-07-20T15:00:00",
      timelineItems: [
        {
          time: "2 PM",
          title: "Llegada y Bienvenida",
          location: "Nuestra Casa",
          mapLink: "",
        },
        {
          time: "3 PM",
          title: "¡La Gran Revelación!",
          location: "El Patio Trasero",
          mapLink: "",
        },
        {
          time: "3:30 PM",
          title: "Celebraciones y Pastel",
          location: "Nuestra Casa",
          mapLink: "",
        },
      ],
    },
    features: {
      genderBetting: true,
      diaperRaffle: false,
      multiEventSchedule: true,
    },
    formSections: ["main-details", "colors-and-style", "event-schedule"],
  },
  "graduation-celebration": {
    name: "Celebración de Graduación",
    thumbnail: "/branding/portadas/portada-graduation-formal.png",
    category: "Graduación",
    description: "Una celebración de logros y nuevos comienzos.",
    font: "font-serif",
    defaultFont: "Great Vibes",
    fonts: ["Roboto Slab", "Oswald", "Anton", "Bebas Neue"],
    palettes: [
      { name: "Muted Earth", primary: "#8B8682", text: "#4A4B4D", background: "#ffffff" },
    ],
    defaultData: {
      primaryColor: "#8B8682",
      textColor: "#4A4B4D",
      backgroundColor: "#F9F8F6",
      heroTitle: "Celebrando la Graduación de",
      heroNames: "Gabriela Alcaraz",
      degreeType: "Ingeniería en Ciencias Computacionales",
      timelineTitle: "Programa del Evento",
      timelineItems: [
        {
          time: "6 PM",
          title: "Ceremonia de Graduación",
          location: "Universidad"
        },
        {
          time: "8 PM", title: "Cena",
          location: "Salon de eventos La Hacienda"
        },
      ],
      tribute: "Un agradecimiento sincero a mi familia y amigos.",
      futurePlansTitle: "Planes Futuros",
      futurePlans: "Próximo destino: Maestría!",
      galleryImages: [
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Graduation/graduation-cover.jpg",
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Graduation/grad1.jpg",
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Graduation/grad2.jpg",
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Graduation/grad3.jpg",
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Graduation/grad4.jpg",
      ],
    },
    features: {
      gallery: true,
      tributeSection: true,
      futurePlans: true,
    },
    formSections: [
      'main-details',
      'colors-and-style',
      'event-schedule',
      'tribute',
      'future-plans'
    ],
  },
  "baby-shower-whimsical": {
    name: "Baby Shower",
    thumbnail: "/branding/portadas/portada-babyShower.png",
    category: "Baby Shower",
    description: "Fiesta de baby shower",
    font: "font-sans",
    defaultFont: "Quicksand",
    fonts: ["Quicksand", "Nunito", "Comfortaa"],
    palettes: [
      { name: "Pastel Blue", primary: "#81d4fa", text: "#01579b", background: "#ffffff" },
      { name: "Pastel Pink", primary: "#f8bbd0", text: "#880e4f", background: "#ffffff" },
    ],
    defaultData: {
      primaryColor: "#81d4fa",
      textColor: "#01579b",
      backgroundColor: "#e3f2fd",
      babyName: "Daniel",
      parentsNames: "Carolina & Miguel",
      event_date: "2026-09-20T14:00:00",
      locationName: "Nuestro Hogar",
      mainVenueAddress: "123 Calle Principal, Colonia, BC",
      rsvpDeadline: "10 de septiembre de 2026",
      rsvpContact: "rsvp@example.com",
      giftRegistryUrl: "https://www.babylist.com",
      giftTitle: "Mesa de Regalos",
      giftMessage: "Tu presencia es nuestro mayor regalo. Pero si deseas obsequiarnos algo, hemos preparado una mesa de regalos con cariño.",
      giftButtonText: "Ver Opciones de Regalo",
      heroTitle: "Celebrando la próxima llegada de",
      heroNames: "Daniel",
      timelineTitle: "Detalles de la Fiesta",
      timelineItems: [], // No timeline for this template by default
    },
    features: {
      // Features can be added here if needed
    },
    formSections: [
      'main-details',
      'colors-and-style',
      'gift-registry',
    ],
  },
  "gender-reveal-bees": {
    name: "Revelación de Género - Tema Abejas",
    thumbnail: "/branding/portadas/portada-gender-bee.png",
    category: "Baby Shower",
    description: "Invitación de revelación de género con tema de abejas.",
    font: "font-sans",
    defaultFont: "Quicksand",
    fonts: ["Quicksand", "Nunito", "Comfortaa"],
    palettes: [
      { name: "Sunny Yellow", primary: "#facc15", text: "#44403c", background: "#ffffff" },
    ],
    defaultData: {
      primaryColor: "#facc15",
      textColor: "#44403c",
      backgroundColor: "#FEF9D1",
      parentsNames: "Familia Alcaraz",
      heroTitle: "What will baby bee?",
      heroNames: "Bebe en camino",
      timelineTitle: "Party Details",
      heroSubtitle: "Acompáñanos a descubrir si tendremos un niño o una niña",
      event_date: "2026-06-12T14:00:00",
      timeSubtitle: "Bocadillos, juegos y mucha diversión",
      locationName: "Los Jardines",
      mainVenueAddress: "123 Calle Floral, Mx",
      location: "",
      giftRegistryUrl: "https://www.amazon.com",
      giftTitle: "Mesa de Regalos",
      giftMessage: "Tu presencia es nuestro mayor regalo. Pero si deseas obsequiarnos algo, hemos preparado una mesa de regalos con cariño.",
      giftButtonText: "Ver Opciones de Regalo",
      rsvpDeadline: "1ero de junio de 2026",
      timelineItems: [],
    },
    features: {
      genderBetting: true,
    },
    formSections: [
      'main-details',
      'colors-and-style',
      'gift-registry',
    ],
  },
  "scrapbook-graduation": {
    name: "Graduación - Moderno",
    thumbnail: "/branding/portadas/portada-grad-cool.png",
    category: "Graduación",
    description: "A fun, scrapbook-style invitation for graduates.",
    font: "font-mono",
    defaultFont: "Permanent Marker",
    fonts: ["Permanent Marker", "Caveat", "Courier Prime"],
    palettes: [
      { name: "Pink & Black", primary: "#FF1493", text: "#1A1A1A", background: "#ffffff" },
    ],
    defaultData: {
      primaryColor: "#FF1493",
      textColor: "#1A1A1A",
      backgroundColor: "#F4EFE6",
      heroTitle: "¡Por fin terminé!\nMe encantaría invitarte a ser parte\nde mi graduación y festejar conmigo",
      heroNames: "Samantha Baker",
      timelineTitle: "Event Schedule",
      hero_image_url: "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Graduation/grad-profile.png",
      guestbookPolaroidImage: "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Graduation/graduation-cover.jpg",
      discoBallImage: "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Graduation/discoball.png",
      starBalloonImage: "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Graduation/star.png",
      event_date: "2026-03-06T19:00:00",
      timelineItems: [
        { time: "7:00 PM", title: "Ceremonia", location: "Auditorio Principal" },
        { time: "9:00 PM", title: "Fiesta", location: "Salón de eventos" },
      ],
    },
    features: {
      multiEventSchedule: true,
    },
    formSections: [
      'main-details',
      'colors-and-style',
      'event-schedule',
    ],
  },
  "modern-event": {
    name: "Modern Event",
    thumbnail: "/branding/portadas/general.png", 
    category: "General",
    description: "A clean and modern design for any occasion, from parties to get-togethers.",
    font: "font-sans",
    defaultFont: "Inter",
    fonts: ["Inter", "Poppins", "Lexend", "Space Grotesk"],
    palettes: [
      { name: "Indigo & Pink", primary: "#4f46e5", secondary: "#ec4899", background: "#f8fafc", text: "#1e293b" },
      { name: "Teal & Lime", primary: "#0d9488", secondary: "#84cc16", background: "#f0fdfa", text: "#1e293b" },
      { name: "Slate & Amber", primary: "#475569", secondary: "#f59e0b", background: "#f8fafc", text: "#1e293b" },
    ],
    defaultData: {
      primaryColor: "#4f46e5",
      secondaryColor: "#ec4899",
      backgroundColor: "#f8fafc",
      textColor: "#1e293b",
      buttonTextColor: "#ffffff",
      heroTitle: "You're Invited To",
      heroNames: "A Celebration",
      timelineTitle: "Event Schedule",
      eventDescription: "Join us for a special get-together filled with joy, laughter, and unforgettable moments.",
      event_date: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
      locationName: "The Central Loft",
      mainVenueAddress: "123 Main Street, Downtown",
      rsvpDeadline: new Date(new Date().setDate(new Date().getDate() + 23)).toISOString(),
      hostNames: "The Hosts",
      timelineItems: [
        { time: "7:00 PM", title: "Arrival & Welcome Drinks", location: "Main Hall" },
        { time: "8:00 PM", title: "Dinner is Served", location: "Dining Area" },
        { time: "9:30 PM", title: "Music & Mingling", location: "Lounge" },
      ],
    },
    features: {
      multiEventSchedule: true,
    },
    formSections: [
      'main-details',
      'colors-and-style',
      'event-schedule',
    ],
  },
  "old-money-wedding": {
    name: "Boda - Estilo Old Money",
    thumbnail: "/branding/portadas/portada-oldMoney.png",
    category: "Boda",
    description: "An elegant and timeless wedding invitation with a classic, sophisticated feel.",
    font: "font-serif",
    defaultFont: "Cormorant Garamond",
    fonts: ["Cormorant Garamond", "Playfair Display", "Bodoni Moda", "Lora"],
    palettes: [
      { name: "Classic Gold", primary: "#9a825e", text: "#292524", background: "#fcfbf9" },
    ],
    defaultData: {
      primaryColor: "#9a825e",
      textColor: "#292524",
      backgroundColor: "#fcfbf9",
      hero_image_url: "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/oldMoney/fondo-oldmoney.jpg",
      heroTitle: "Nuestra Boda",
      heroNames: "Yoselin & Ivan",
      timelineTitle: "Itinerario",
      partner1Name: "Yoselin",
      partner2Name: "Ivan",
      event_date: "2024-11-16T13:00:00",
      quote: "Tú siempre serás mi referente del amor en pareja, por qué siempre quise esto y tú me lo has regalado",
      partner1Parents: ["Efrain Albiter Hernández", "Rocio Esquivel Garcia"],
      partner2Parents: ["Lazaro Meneses Ramirez", "Ana Maria Vazquez Nieves"],
      godparents: [{ name: "Jorge Albiter Hernández & Janeth Benitez Rebollar", role: "Padrinos" }],
      venueDividerText: "~",
      timelineItems: [
        { time: "1:00 PM", title: "Ceremonia", location: "Parroquia de San Luis Obispo de Huamantla\nC. Hidalgo Manzana 031, San Luis Huexotla\n56220 San Luis Huexotla, Méx", mapLink: "" },
        { time: "3:30 PM", title: "Recepción", location: "Rancho Caballerizas\nAv. Aguilas 36, Lomas de San Esteban\n56257 Texcoco de Mora, Méx", mapLink: "" },
      ],
      dressCode: {
        man: "Formal",
        woman: "Formal",
        pinterestUrlMan: "https://pin.it/5hSkwuONE",
        pinterestUrlWoman: "https://pin.it/57zbcpMb7",
      },
      dressCodeTitle: "Vestimenta",
      dressCodeDetails: "Blanco, Beige, Gris, Rosa Palo, Lila",
      galleryImages: [
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/oldMoney/oldMoney3.png",
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/oldMoney/oldMoney1.png",
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/oldMoney/oldMoney2.png",
        "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Romantic/romantic-3.jpg"
      ],
    },
    features: {
      multiEventSchedule: true,
      gallery: true,
      parentsAndGodparents: true,
      guestCount: true,
    },
    formSections: [
      'main-details',
      'colors-and-style',
      'dress-code',
      'event-schedule',
      'gallery',
    ],
  },
  'sports-birthday': {
    name: "Sports Birthday",
    thumbnail: "/branding/portadas/portada-soccer.png",
    category: "Cumpleaños Infantil",
    description: "A high-energy, modern template for a sports-themed birthday.",
    font: "font-sans",
    defaultFont: "Inter",
    fonts: ["Inter", "Poppins", "Lexend", "Space Grotesk"],
    palettes: [],
    defaultData: {
      heroTitle: "You're Invited!",
      timelineTitle: "Game Day Schedule",
      heroNames: "Alex",
      age: 7,
      photoUrl: "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Kids-Bdy/futbol-kid.jpg",
      location: "The Local Park",
      event_date: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
      parentalNotes: "Bring your A-game! We'll have pizza and cake after the match.",
      extraInfo: "Don't forget your water bottles!",
      timelineItems: [
        { time: "2:00 PM", title: "Warm-up & Drills", location: "Main Field" },
        { time: "3:00 PM", title: "The Big Game!", location: "Main Field" },
        { time: "4:30 PM", title: "Awards & Cake", location: "Picnic Area" },
      ],
    },
    features: {
      parentalNotes: true,
      ageSpecificThemes: [],
    },
    formSections: [
      'main-details',
      'colors-and-style',
    ]
  },
  'princess-birthday': {
    name: "Princess Birthday",
    thumbnail: "/branding/portadas/portada-princesa.png",
    category: "Cumpleaños Infantil",
    description: "A magical and elegant birthday invitation for a little princess.",
    font: "font-serif",
    defaultFont: "Dancing Script",
    fonts: ["Playfair Display", "Lora", "Cormorant Garamond", "Dancing Script"],
    palettes: [
      { name: "Blush & Gold", primary: "#FDF6F8", text: "#C28B96", secondary: "#B89766", dark: "#5A4A42", background: "#ffffff" },
    ],
    defaultData: {
      heroTitle: "Estas invitado a la celebración de cumpleaños de",
      timelineTitle: "Celebración Real",
      timelineItems: [],
      heroNames: "Olivia",
      age: 4,
      event_date: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
      startTime: "12:00 PM",
      endTime: "2:00 PM",
      location: "Residencia Aguacaliente",
      rsvpDateText: "15 de julio",
      parentalNotes: "Favor de traer calcetas extras y cambio de ropa",
      photoUrl: "https://ykgyfxtzjedgastsuuaj.supabase.co/storage/v1/object/public/invitation-images/public/Kids-Bdy/princesa.png",
      backgroundColor: "#FDF6F8",
      textPrimary: '#C28B96',
      textGold: '#B89766',
      textDark: '#5A4A42',
    },
    features: {
      parentalNotes: true,
      ageSpecificThemes: [],
    },
    formSections: [
      'main-details',
      'colors-and-style',
    ]
  },
  'masquerade-xv': {
    name: 'XV Años - Baile de Máscaras',
    thumbnail: '/branding/portadas/portada-antifaz.png',
    category: 'XV Años',
    description: 'Una elegante y misteriosa invitación para un baile de máscaras de XV años.',
    font: 'font-serif',
    defaultFont: 'Playfair Display',
    fonts: ['Playfair Display', 'Lora', 'Cormorant Garamond'],
    palettes: [
      { name: 'Masquerade Gold', primary: '#92005f', text: '#000000', background: '#9f583a', secondary: '#800020' },
    ],
    defaultData: {
      primaryColor: '#800020',
      textColor: '#000000',
      backgroundColor: '#f5e8d5',
      secondaryColor: '#800020',
      hero_image_url: '/vintage2.jpg',
      heroTitle: "Save the Date",
      heroNames: "VALERIA",
      event_date: "2026-11-21T19:00:00",
      locationName: "Tijuana",
      mainVenueAddress: "Tijuana, Baja California, México",
      timelineTitle: "Itinerario de la noche",
      timelineItems: [
        { time: '7:00 PM', title: 'Coctel de Bienvenida'},
        { time: '8:00 PM', title: '1er Tiempo de Cena'},
        { time: '8:15 PM', title: '2do Tiempo de Cena' },
        { time: '8:45 PM', title: '3er Tiempo de Cena' },
        { time: '9:00 PM', title: 'Baile de Valeria & Chambelanes' },
        { time: '9:15 PM', title: 'Brindis' },
        { time: '9:25 PM', title: 'Baile con papás y baile sorpresa' },
        { time: '9:40 PM', title: 'Apertura de pista DJ' },
        { time: '10:00 PM', title: 'Barra de Snacks' },
      ],
      dressCode: {
        woman: 'Vestido de gala y antifaz',
        man: 'Traje formal y antifaz',
        details: 'Paleta de colores: Negro, Guinda, Dorado, Plateado, Rojo.',
      },
    },
    features: {
      multiEventSchedule: true,
      dressCode: true,
      rsvp: true,
      guestCount: true,
    },
    formSections: [
      'main-details',
      'colors-and-style',
      'event-schedule',
      'dress-code',
    ],
  },
};
